"""Band-masking and export core.

UI-agnostic: imports only numpy and Pillow. Both the CLI and the GUI call
these functions; neither front end reimplements any logic found here.

All luminance work happens on a single-channel uint8 numpy array produced
by :func:`load_grayscale`.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
from PIL import Image


class BandingError(ValueError):
    """Raised for invalid inputs (bad breakpoints, unreadable image, ...)."""


# --------------------------------------------------------------------------
# Loading / grayscale conversion
# --------------------------------------------------------------------------

def load_grayscale(path: str | Path, invert: bool = False) -> np.ndarray:
    """Load an image (color or grayscale) as a single-channel uint8 array.

    Alpha, if present, is flattened onto white before conversion so that
    transparent regions band as "light" rather than as arbitrary RGB noise.
    Conversion to "L" uses Pillow's ITU-R 601 luminance weights.
    """
    try:
        img = Image.open(path)
        img.load()
    except (OSError, ValueError) as exc:
        raise BandingError(f"Cannot read image {path}: {exc}") from exc

    if img.mode in ("RGBA", "LA", "PA") or (
        img.mode == "P" and "transparency" in img.info
    ):
        rgba = img.convert("RGBA")
        background = Image.new("RGBA", rgba.size, (255, 255, 255, 255))
        img = Image.alpha_composite(background, rgba)

    gray = np.asarray(img.convert("L"), dtype=np.uint8)
    if invert:
        gray = 255 - gray
    return gray


# --------------------------------------------------------------------------
# Breakpoints and thresholds
# --------------------------------------------------------------------------

def even_breakpoints(n_bands: int) -> list[float]:
    """Percentage breakpoints for ``n_bands`` equal bands: [0, ..., 100]."""
    if n_bands < 1:
        raise BandingError(f"Band count must be >= 1, got {n_bands}")
    return [100.0 * i / n_bands for i in range(n_bands + 1)]


def validate_breakpoints(percentages: list[float]) -> list[int]:
    """Validate percentage breakpoints and map them to luminance thresholds.

    Requirements: first == 0, last == 100, strictly increasing, and the
    mapped 0-255 integer thresholds must also be strictly increasing
    (breakpoints closer than ~0.4% collapse to the same luminance value,
    which would produce an empty band).

    Returns thresholds ``[0, ..., 255]`` with len == len(percentages).
    """
    pcts = [float(p) for p in percentages]
    if len(pcts) < 2:
        raise BandingError("Need at least 2 breakpoints (found %d)" % len(pcts))
    if pcts[0] != 0.0:
        raise BandingError(f"First breakpoint must be 0, got {pcts[0]}")
    if pcts[-1] != 100.0:
        raise BandingError(f"Last breakpoint must be 100, got {pcts[-1]}")
    for lo, hi in zip(pcts, pcts[1:]):
        if hi <= lo:
            raise BandingError(
                f"Breakpoints must be strictly increasing: {lo} -> {hi}"
            )

    thresholds = [round(p / 100.0 * 255.0) for p in pcts]
    for i, (lo, hi) in enumerate(zip(thresholds, thresholds[1:])):
        if hi <= lo:
            raise BandingError(
                f"Breakpoints {pcts[i]}% and {pcts[i + 1]}% map to the same "
                f"luminance value ({lo}); band {i} would be empty. "
                "Spread them at least 0.4% apart."
            )
    return thresholds


# --------------------------------------------------------------------------
# Masks, coverage, overlay
# --------------------------------------------------------------------------

def band_masks(gray: np.ndarray, thresholds: list[int]) -> list[np.ndarray]:
    """Boolean mask per band.

    Band i covers ``thresholds[i] <= v < thresholds[i+1]``; the final band
    is inclusive of its upper bound so 255 is always covered. Every pixel
    lands in exactly one band.
    """
    masks = []
    last = len(thresholds) - 2
    for i in range(last + 1):
        lo, hi = thresholds[i], thresholds[i + 1]
        if i == last:
            masks.append((gray >= lo) & (gray <= hi))
        else:
            masks.append((gray >= lo) & (gray < hi))
    return masks


def coverage(masks: list[np.ndarray]) -> list[float]:
    """Percent of image pixels in each band."""
    total = masks[0].size
    return [100.0 * int(m.sum()) / total for m in masks]


def make_overlay(
    gray: np.ndarray,
    masks: list[np.ndarray],
    colors_rgb: list[tuple[int, int, int]],
) -> np.ndarray:
    """Composite each band's color over the grayscale source (HxWx3 uint8).

    Used by the GUI preview; kept in core so the preview is generated by
    the exact same masks the export uses.
    """
    base = np.repeat(gray[:, :, np.newaxis], 3, axis=2).astype(np.float32)
    out = base.copy()
    for mask, color in zip(masks, colors_rgb):
        tint = np.array(color, dtype=np.float32)
        out[mask] = 0.55 * tint + 0.45 * base[mask]
    return out.astype(np.uint8)


# --------------------------------------------------------------------------
# Export
# --------------------------------------------------------------------------

@dataclass
class BandInfo:
    index: int
    pct_range: tuple[float, float]
    luminance_range: tuple[int, int]  # inclusive
    filename: str
    coverage_pct: float


@dataclass
class Manifest:
    source: str
    width: int
    height: int
    dpi: int
    invert: bool
    white_bg: bool
    bands: list[BandInfo] = field(default_factory=list)

    def to_json(self) -> str:
        return json.dumps(
            {
                "tool": "BurnBands",
                "source": self.source,
                "width": self.width,
                "height": self.height,
                "dpi": self.dpi,
                "invert": self.invert,
                "white_bg": self.white_bg,
                "bands": [
                    {
                        "index": b.index,
                        "pct_range": list(b.pct_range),
                        "luminance_range": list(b.luminance_range),
                        "filename": b.filename,
                        "coverage_pct": round(b.coverage_pct, 4),
                    }
                    for b in self.bands
                ],
                "lightburn_notes": (
                    "Import each band PNG as an image layer in LightBurn. "
                    "DPI is embedded, so use Pass-Through image mode to keep "
                    "physical size. Bands are index-ordered darkest to "
                    "lightest and align pixel-for-pixel when superimposed."
                ),
            },
            indent=2,
        )


def band_filename(index: int, lo: int, hi_inclusive: int) -> str:
    return f"band_{index:02d}_L{lo:03d}-{hi_inclusive:03d}.png"


def export_bands(
    gray: np.ndarray,
    percentages: list[float],
    out_dir: str | Path,
    dpi: int = 300,
    white_bg: bool = False,
    source_name: str = "",
    invert: bool = False,
) -> Manifest:
    """Write one PNG per band plus manifest.json into ``out_dir``.

    Default output: in-band pixels black, everything else fully transparent
    (binary alpha, hard edges). With ``white_bg``: in-band black on white.
    Every PNG is stamped with the given DPI and shares the source's pixel
    dimensions. Band 0 is the darkest band.
    """
    thresholds = validate_breakpoints(percentages)
    masks = band_masks(gray, thresholds)
    cov = coverage(masks)

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    h, w = gray.shape
    manifest = Manifest(
        source=source_name,
        width=w,
        height=h,
        dpi=dpi,
        invert=invert,
        white_bg=white_bg,
    )

    last = len(masks) - 1
    for i, mask in enumerate(masks):
        lo = thresholds[i]
        hi_inclusive = thresholds[i + 1] if i == last else thresholds[i + 1] - 1
        name = band_filename(i, lo, hi_inclusive)

        if white_bg:
            arr = np.where(mask, 0, 255).astype(np.uint8)
            img = Image.fromarray(arr, mode="L")
        else:
            rgba = np.zeros((h, w, 4), dtype=np.uint8)
            rgba[:, :, 3] = mask.astype(np.uint8) * 255
            img = Image.fromarray(rgba, mode="RGBA")

        img.save(out_dir / name, format="PNG", dpi=(dpi, dpi))

        manifest.bands.append(
            BandInfo(
                index=i,
                pct_range=(float(percentages[i]), float(percentages[i + 1])),
                luminance_range=(lo, hi_inclusive),
                filename=name,
                coverage_pct=cov[i],
            )
        )

    (out_dir / "manifest.json").write_text(manifest.to_json())
    return manifest
